config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registration', sessions: 'sessions', passwords: 'passwords'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :polls do
    resource :comments, only: [:create]
    resources :follows, only: [:create, :destroy]
    resource :option_a, only: [:create, :update, :destroy]
    resource :option_b, only: [:create, :update, :destroy]
    resource :visitor_option_a, only: [:create, :update, :destroy]
    resource :visitor_option_b, only: [:create, :update, :destroy]
  end
  
  resource :profiles, only: [:show]
  resources :privacy, only: [:index]
  
  namespace :api do
    resource :registrations, only: [:create]
    resource :sessions, only: [:create]
    resources :polls, only: [:create, :index, :show]
    resources :users, only: [:show]
    resource :comments, only: [:create, :show]
    resource :follows, only: [:create, :show, :destroy]
    resource :votes, except: [:index, :edit, :new]
  end
  
  root "polls#index"
end

app/views/shared/_comment-form.erb
<%= form_tag poll_comment_path(Comment.find(id).poll, Comment.find(id)), id: "edit-comment-form-#{id}", class: 'comment-edit-form', method: :put, remote: true do %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<% end %>

app/views/shared/_create.html.erb
<dialog hidden class="create-modal modal" id="create-modal">
  <div class="modal__inner">
    <div class="modal__top">
      <div>
        <h2 class="modal__title">Create a poll</h2>
        <p class="create-modal__subtitle">This or That can take it from here.</p>
      </div>
      <button href="/" class="modal__cancel" data-module="modal" aria-controls="create-modal">Cancel<i class="icon-expired"></i></button>
    </div>
    <%= form_for Poll.new, as: :poll, url: polls_path, multipart: true, remote: true, html: {id: 'poll-form'} do |f| %>
      <div id="poll-error-messages"></div>

      <div class="create-modal__fields__name-poll">
        <h3><span class="form__required">*</span>Give your poll a title <em id="poll-char-count-title">(max 30 characters)</em></h3>
        <%= f.text_field :title, placeholder: "ex: should I buy this or that?", id: "poll-title" %>
      </div>

      <div class="create-modal__fields__option-labels">
        <div class="create-modal__fields__option-label">
          <h3><span class="form__required">*</span>Option A <em id="poll-char-count-opta">(max 25 characters)</em></h3>
          <%= f.text_field :option_a, placeholder: "ex: pizza", id: "poll-option-a" %>
        </div>
        <div class="create-modal__fields__option-label create-modal__fields__option-label--right">
          <h3><span class="form__required">*</span>Option B <em id="poll-char-count-optb">(max 25 characters)</em></h3>
         <%= f.text_field :option_b, placeholder: "ex: tacos", id: "poll-option-b" %>
        </div>
      </div>

      <h3>Upload photos <em>(optional)</em></h3>
      <div class="create-modal__fields__photos">
        <div class="create-modal__fields__photo create-modal__fields__photo--left">
          <h4><i class="icon-upload"></i> Choose from your device</h4>
          <%= f.label :option_a_img, "browse +" %>
          <%= f.file_field :option_a_img, class: "create-modal__fields__photo__browse", id: "poll_option_a_img", accept: ".jpg, .jpeg, .png", :data => {:module => 'upload', :targetstring => '#poll_option_a_img_filename'} %>

          <div class="photo--left__preview">
            <p id="poll_option_a_img_filename">no file chosen</p>
          </div>
          <p class="create-modal__OR">OR</p>
          <h4>Copy and paste a URL</h4>
          <%= f.url_field :option_a_url %>
        </div>
        <div class="create-modal__fields__photo create-modal__fields__photo--right">
          <h4><i class="icon-upload"></i> Choose from your device</h4>
          <%= f.label :option_b_img, "browse +" %>
          <%= f.file_field :option_b_img, class: "create-modal__fields__photo__browse", id: "poll_option_b_img", accept: ".jpg, .jpeg, .png", :data => {:module => 'upload', :targetstring => '#poll_option_b_img_filename'} %>
          <div class="photo--right__preview">
             <p id="poll_option_b_img_filename">no file chosen</p>
          </div>
          <p class="create-modal__OR">OR</p>
          <h4>Copy and paste a URL</h4>
          <%= f.url_field :option_b_url %>
        </div>
      </div>

      <h3>Allow others to vote for:</h3>
      <div class="create-modal__fields__duration">
          <div class="create-modal__fields__duration__input">
            <%= f.number_field "expire[days]", value: 7, min: 0, id: "poll_expire_days" %>
            <%= f.label :expire_days, "days" %>
          </div>
          <div class="create-modal__fields__duration__input">
            <%= f.number_field "expire[hours]", value: 0, min:0,  id: "poll_expire_hours" %>
            <%= f.label :expire_hours, "hours" %>
          </div>
          <div class="create-modal__fields__duration__input">
            <%= f.number_field "expire[mins]", value: 0, step: 10, min: 0, max: 60, id: "poll_expire_mins" %>
            <%= f.label :expire_mins, "minutes" %>
          </div>
      </div>

      <%= f.submit "Submit poll", class: "create-modal__submit" %>
    <% end %>
  </div>
</dialog>

app/views/shared/_expired-options.html.erb
<div class="poll__options">
  <% if poll.vote_count > 0 %>
    <%= link_to 'javascript:void(0)', method: :get, id: "option-a-#{poll.id}", class: "option-poll poll__options__option", remote: true do %>
      <% if poll.get_option_a_img.present? %>
        <p id="option-a-text-<%= poll.id %>" class="option-text--hidden"><%= poll.option_a %></p>
      <% else %>
        <p id="option-a-text-<%= poll.id %>"><%= poll.option_a %></p>
      <% end %>
      <span id="option-a__percentage-<%= poll.id %>"></span>
    <% end %>

    <style>
        #option-a-<%= poll.id %> {
          width: <%= poll.fraction_of_votes(0) * 100 %>%;
        }
        #option-b-<%= poll.id %> {
          width: <%= poll.fraction_of_votes(1) * 100 %>%;
        }
    </style>

    <%= link_to 'javascript:void(0)', method: :get, id: "option-b-#{poll.id}", class: "option-poll poll__options__option", remote: true do %>
      <% if poll.get_option_b_img.present? %>
        <p id="option-b-text-<%= poll.id %>" class="option-text--hidden"><%= poll.option_b %></p>
      <% else %>
        <p id="option-b-text-<%= poll.id %>"><%= poll.option_b %></p>
      <% end %>
      <span id="option-b__percentage-<%= poll.id %>"></span>
    <% end %>
    </div>
    <script>
      var optionAText = document.querySelector('#option-a-text-' + <%= poll.id %>)
      var optionBText = document.querySelector('#option-b-text-' + <%= poll.id %>)
      if (<%= poll.fraction_of_votes(0) %> !== 0) {
        var optionAPercentageId = '#option-a__percentage-' + <%= poll.id %>;
        var optionAPercentage = document.querySelector(optionAPercentageId)
        optionAPercentage.innerHTML = Math.round(<%= (poll.fraction_of_votes(0) * 100) %>) + '%';
        optionAText.innerHTML = '<%= poll.option_a %>'
      } else {
        optionAText.innerHTML = ''
      }
      if (<%= poll.fraction_of_votes(1) %> !== 0) {
        var optionBPercentageId = '#option-b__percentage-' + <%= poll.id %>;
        var optionBPercentage = document.querySelector(optionBPercentageId)
        optionBPercentage.innerHTML = Math.round(<%= (poll.fraction_of_votes(1) * 100) %>) + '%';
        optionBText.innerHTML = '<%= poll.option_b %>'
      } else {
        optionBText.innerHTML = ''
      }
    </script>
  <% else %>
    <%= render 'shared/option-links', poll: poll, http_methodA: nil, http_methodB: nil, optionA: nil, optionB: nil %>
    </div>
  <% end %>

app/views/shared/_follow.html.erb
<% if user_signed_in? %>
    <% if current_user.get_follow(poll.id).present? %>
        <%= link_to poll_follow_path(poll, current_user.get_follow(poll.id)), method: :delete, remote: true, class: "follow-poll", id: "poll-follow-path-#{poll.id}" do %>
            <i class="icon-following" id="follower-<%= poll.id %>"></i>
            <span id="poll-follow-<%= poll.id %>">following</span>
        <% end %>
    <% else %>
        <%= link_to poll_follows_path(poll), method: :post, remote: true, class: "follow-poll", id: "poll-follow-path-#{poll.id}" do %>
            <i class="icon-follow" id="follower-<%= poll.id %>"></i>
            <span id="poll-follow-<%= poll.id %>">follow</span>
        <% end %>
    <% end %>
<% else %>
    <%= link_to poll_follows_path(poll), method: :post, remote: true, class: "follow-poll", id: "poll-follow-path-#{poll.id}" do %>
        <i class="icon-follow" id="follower-<%= poll.id %>"></i>
        <span id="poll-follow-<%= poll.id %>">follow</span>
    <% end %>
<% end %>

app/views/shared/_forgot-password.html.erb
<dialog hidden class="modal forgot-password" id="forgot-password">
  <div class="modal__inner">
    <div class="modal__top">
      <h2 class="modal__title">Password Reset</h2>
      <button href="#TODO" class="modal__cancel" data-module="modal" aria-controls="forgot-password">Cancel<i class="icon-expired"></i></button>
    </div>
    <div id="password-request-messages">
    
    </div>
    <%= form_for(User.new, as: :user, url: password_path(:user), remote: true, html: { method: :post, id: "password-request-form" }) do |f| %>

      <div class="form__fields__field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>

      <div class="form__fields__action">
        <%= f.submit "Send password reset instructions", class: "form__button" %>
      </div>
    <% end %>
  </div>
</dialog>

app/views/shared/_header.html.erb
<header class="header">
  <a href="/" class="header__logo">
    <%= inline_svg "logo.svg", class: 'header__logo' %>
  </a>
  <ul class="header__utility-nav">
    <% if user_signed_in? %>
      <li id="poll-feed" class="header__feed  header__utility-nav--active">
        <%= link_to 'Feed', polls_path, method: :get %>
    </li>
    <% end %>
    <% if user_signed_in? %>
      <li class="header__create" data-module="modal" aria-controls="create-modal">
    <% else %>
      <li class="header__create header__create--fixed" data-module="modal" aria-controls="sign-up">
    <% end %>
      <a href="#">
        <span class="header__create__text--hidden">Create a Poll</span>
        <%= inline_svg "create_poll.svg" %>
      </a>
    </li>
    <% if user_signed_in? %>
      <li id="poll-mypolls" class="header__your-polls">
        <%= link_to 'My Polls', polls_path(filter: 'mypolls'), method: :get %>
      </li>
      <li id="poll-following" class="header__following">
        <%= link_to 'Following', polls_path(filter: 'following'), method: :get %>
      </li>
      <li class="header__username">
        <a href="javascript:void(0)"class="header__username__arrow" data-module="dropdown" aria-controls="#header__dropdown"><%= current_user.username %>
        </a>
        <ul class="header__dropdown" id="header__dropdown">
          <li class="header__dropdown__item">
            <a href="#" data-module="modal" aria-controls="forgot-password">
             reset password
            </a>
          </li>
          <li class="header__dropdown__item">
            <%= link_to "log out", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </li>
    <% else %>
      <li class="header__sign-up header__session-links">
        <a href="#" data-module="modal" aria-controls="sign-up">
          Sign up
        </a>
      </li>
      <li class="header__log-in header__session-links">
        <a href="#" data-module="modal" aria-controls="log-in">
          Log in
        </a>
      </li>
    <% end %>
  </ul>
</header>

app/views/shared/_login.html.erb
<dialog hidden class="modal log-in" id="log-in">
  <div class="modal__inner">
    <div class="modal__top">
      <h2 class="modal__title">Log in</h2>
      <button class="modal__cancel" data-module="modal" aria-controls="log-in">Cancel<i class="icon-expired"></i></button>
    </div>
    <%= form_for(User.new, as: :user, url: session_path(:user), remote: true, html: {id: "login-form"}) do |f| %>
      <div class="form__fields">
        <!-- Error messages from Devise -->
        <div id="login-error-messages" class="form__error-message">
        </div>
        <div class="form__fields__field">
          <%= f.label :email %>
          <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
        </div>

        <div class="form__fields__field">
          <%= f.label :password %>
          <%= f.password_field :password, autocomplete: "off" %>
        </div>

        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

        <div class="form__fields__actions log-in__submit">
          <%= f.submit "Log in", class: "form__button" %>
        </div>
      </div>
    <% end %>
  </div>
  <button data-module="modal" aria-controls="forgot-password" class="forgot-password__button">Forgot Password?</button>
  <div class="form__bottom-prompt">
    <p>New here?</p>
    <button data-module="modal" aria-controls="sign-up">Sign up</button>
  </div>
</dialog>

app/views/shared/_options.html.erb
<div class="poll__options">
  <% if user_signed_in? %>
    <% if current_user.has_voted?(poll.id) %>
      <% if current_user.get_vote(poll.id).option == 0 %>
        <%= render 'shared/option-links', poll: poll, http_methodA: :delete, http_methodB: :put, optionA: poll.fraction_of_votes(0), optionB: poll.fraction_of_votes(1), pathA: poll_option_a_path(poll), pathB: poll_option_b_path(poll), classNameA: 'poll__options__option--selected', classNameB: '' %>
      <% else %>
        <%= render 'shared/option-links', poll: poll, http_methodA: :put, http_methodB: :delete, optionA: poll.fraction_of_votes(0), optionB: poll.fraction_of_votes(1), pathA: poll_option_a_path(poll), pathB: poll_option_b_path(poll), classNameA: '', classNameB: 'poll__options__option--selected' %>
      <% end %>
      </div>
      <script>
        var optionA = document.querySelector('#option-a-' + <%= poll.id %>)
        var optionB = document.querySelector('#option-b-' + <%= poll.id %>)
        var optionAText = document.querySelector('#option-a-text-' + <%= poll.id %>)
        var optionBText = document.querySelector('#option-b-text-' + <%= poll.id %>)
        if (<%= poll.fraction_of_votes(0) %> !== 0) {
          var optionAPercentageId = '#option-a__percentage-' + <%= poll.id %>;
          var optionAPercentage = document.querySelector(optionAPercentageId)
          optionAPercentage.innerHTML = Math.round(<%= (poll.fraction_of_votes(0) * 100) %>) + '%';
          optionAText.innerHTML = '<%= poll.option_a %>'
          optionA.classList.remove('poll__options__option--no-votes')
        } else {
          optionAText.innerHTML = ''
          optionA.classList.add('poll__options__option--no-votes')
        }
        if (<%= poll.fraction_of_votes(1) %> !== 0) {
          var optionBPercentageId = '#option-b__percentage-' + <%= poll.id %>;
          var optionBPercentage = document.querySelector(optionBPercentageId)

          optionBPercentage.innerHTML = Math.round(<%= (poll.fraction_of_votes(1) * 100) %>) + '%';
          optionBText.innerHTML = '<%= poll.option_b %>'
          optionB.classList.remove('poll__options__option--no-votes')
        } else {
          optionBText.innerHTML = ''
          optionB.classList.add('poll__options__option--no-votes')
        }
      </script>
    <% else %>
      <%= render 'shared/option-links', poll: poll, http_methodA: :post, http_methodB: :post , optionA: nil, optionB: nil, pathA: poll_option_a_path(poll), pathB: poll_option_b_path(poll) %>
      </div>
    <% end %>
  <% else %>
    <% if poll.has_visitor_voted?(@ip) %>
      <% if poll.get_visitor_vote(@ip).option == 0 %>
        <%= render 'shared/option-links', poll: poll, http_methodA: :delete, http_methodB: :put, optionA: poll.fraction_of_votes(0), optionB: poll.fraction_of_votes(1), pathA: poll_visitor_option_a_path(poll), pathB: poll_visitor_option_b_path(poll), classNameA: 'poll__options__option--selected', classNameB: '' %>
      <% else %>
        <%= render 'shared/option-links', poll: poll, http_methodA: :put, http_methodB: :delete, optionA: poll.fraction_of_votes(0), optionB: poll.fraction_of_votes(1), pathA: poll_visitor_option_a_path(poll), pathB: poll_visitor_option_b_path(poll), classNameB: 'poll__options__option--selected', classNameA: '' %>
      <% end %>
      </div>
      <script>
        var optionA = document.querySelector('#option-a-' + <%= poll.id %>)
        var optionB = document.querySelector('#option-b-' + <%= poll.id %>)
        var optionAText = document.querySelector('#option-a-text-' + <%= poll.id %>)
        var optionBText = document.querySelector('#option-b-text-' + <%= poll.id %>)
        if (<%= poll.fraction_of_votes(0) %> !== 0) {
          var optionAPercentageId = '#option-a__percentage-' + <%= poll.id %>;
          var optionAPercentage = document.querySelector(optionAPercentageId)
          optionAPercentage.innerHTML = Math.round(<%= (poll.fraction_of_votes(0) * 100) %>) + '%';
          optionAText.innerHTML = '<%= poll.option_a %>'
          optionA.classList.remove('poll__options__option--no-votes')
        } else {
          optionAText.innerHTML = ''
          optionA.classList.add('poll__options__option--no-votes')
        }
        if (<%= poll.fraction_of_votes(1) %> !== 0) {
          var optionBPercentageId = '#option-b__percentage-' + <%= poll.id %>;
          var optionBPercentage = document.querySelector(optionBPercentageId)

          optionBPercentage.innerHTML = Math.round(<%= (poll.fraction_of_votes(1) * 100) %>) + '%';
          optionBText.innerHTML = '<%= poll.option_b %>'
          optionB.classList.remove('poll__options__option--no-votes')
        } else {
          optionBText.innerHTML = ''
          optionB.classList.add('poll__options__option--no-votes')
        }
      </script>
    <% else %>
      <%= render 'shared/option-links', poll: poll, http_methodA: :post, http_methodB: :post, optionA: nil, optionB: nil, pathA: poll_visitor_option_a_path(poll), pathB: poll_visitor_option_b_path(poll) %>
      </div>
    <% end %>
  <% end %>

app/views/shared/_poll-detailed.html.erb
<% if single_poll.get_option_a_img.present? %>
  <style>
    #option-a-<%= single_poll.id %> {
      background-image: linear-gradient(rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05)), url(<%= single_poll.get_option_a_img %>);
      background-size: cover;
      color: #fff;
    }

    #option-a-<%= single_poll.id %>:after {
        background: radial-gradient(rgba(97, 183, 242, 1) 50%, rgba(97, 183, 242, 0.3));
        border-top-left-radius: 100%;
        border-top-right-radius: 100%;
        bottom: -50%;
        content: "<%= single_poll.option_a.html_safe %>";
    }

    #option-b-<%= single_poll.id %> {
      background-image: linear-gradient(rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05)), url(<%= single_poll.get_option_b_img %>);
      color: #fff;
    }

    #option-b-<%= single_poll.id %>:after {
      background: radial-gradient(rgba(252, 185, 44, 1) 50%, rgba(252, 185, 44, 0.6));
      border-radius: 20px;
      bottom: -52%;
      content: "<%= single_poll.option_b.html_safe %>";
    }
  </style>
<% end %>

<script>
  let activeClass = "header__utility-nav--active";
  document.querySelector(`.${activeClass}`).classList.remove(activeClass);
</script>

<article class="poll poll-detailed">
  <div class="poll__content">
    <h2><%= single_poll.title %></h2>
    <div class="poll__meta">
      <p><%= single_poll.user.username %></p>
      <ul>
        <li><i class="icon-fire"></i><span id="poll-vote-count-<%= single_poll.id %>"><%= pluralize(single_poll.vote_count, "vote") %></span></li>
        <li>
          <% if single_poll.expired? %>
            <i class="icon-expired"></i><span>expired</span>
          <% else %>
            <i class="icon-clock"></i><span><%= single_poll.time_left %> left</span>
          <% end %>
        </li>
      </ul>
    </div>

    <% if single_poll.expired? || single_poll.owned_by?(current_user) %>
      <%= render 'shared/static-options', poll: single_poll %>
    <% else %>
      <%= render 'shared/options', poll: single_poll %>
    <% end %>
    
    <ul class="poll__actions">
      <li class="poll__actions__comments poll__actions__action">
        <%= link_to single_poll do %>
          <i class="icon-comment"></i>
          <span><%= pluralize(single_poll.comment_count, "comment") %></span>
        <% end %>
      </li>

      <% if !single_poll.owned_by?(current_user) %>
        <li class="poll__actions__action">
          <%= render 'shared/follow', poll: single_poll %>
        </li>
      <% end %>
      <li class="poll__actions__action">
        <%= link_to 'javascript:void(0)', id:"poll-copy-link-#{single_poll.id}", class: 'copy-link-poll', value: poll_url(single_poll) do %>
          <i class="icon-link"></i>
          <span id="poll-copy-span-<%= single_poll.id %>">copy link</span>
        <% end %>
      </li>
      <% if single_poll.owned_by?(current_user) %>
        <li class="poll__actions__action">
        <%= link_to poll_path(single_poll), method: :delete, id: '', class: '' do %>
            <i class="icon-trash"></i>
            <span>delete poll</span>
        <% end %>
        </li>
      <% end %>

    </ul>
  </div>
</article>

app/views/shared/_poll.html.erb
<style>
  <% if poll.get_option_a_img.present? %>
      #option-a-<%= poll.id %> {
        background-image: linear-gradient(rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05)), url(<%= url_for(poll.get_option_a_img) %>);
      }
      #option-a-<%= poll.id %>:after {
          background: radial-gradient(rgba(97, 183, 242, 1) 50%, rgba(97, 183, 242, 0.3));
          border-top-left-radius: 100%;
          border-top-right-radius: 100%;
          bottom: -50%;
          content: "<%= poll.option_a.html_safe %>";
          left: 5%;
      }
  <% end %>

  <% if poll.get_option_b_img.present? %>
    #option-b-<%= poll.id %> {
      background-image: linear-gradient(rgba(0, 0, 0, 0.05), rgba(0, 0, 0, 0.05)), url(<%= url_for(poll.get_option_b_img) %>);
    }
    #option-b-<%= poll.id %>:after {
      background: radial-gradient(rgba(252, 185, 44, 1) 50%, rgba(252, 185, 44, 0.6));
      border-radius: 20px;
      bottom: -52%;
      content: "<%= poll.option_b.html_safe %>";
      left: 5%;
    }
  <% end %>
</style>

<article class="poll" id="article-poll-<%= index %>">
  <% if user_signed_in? && poll.user == current_user %>
    <% if poll.expired? %>
      <div class="poll__meta poll__meta--users-poll poll__meta--users-poll--expired">
    <% else %>
      <div class="poll__meta poll__meta--users-poll">
    <% end %>
  <% else %>
    <% if poll.expired? %>
      <div class="poll__meta poll__meta--expired">
    <% else %>
      <div class="poll__meta">
    <% end %>
  <% end %>
    <p><%= poll.user.username %></p>
    <ul>
      <li><i class="icon-fire"></i><span id="poll-vote-count-<%= poll.id %>"><%= pluralize(poll.vote_count, "vote") %></span></li>
      <li>
        <% if poll.expired? %>
          <i class="icon-expired"></i><span>expired</span>
        <% else %>
          <i class="icon-clock"></i><span><%= poll.time_left %> left</span>
        <% end %>
      </li>
    </ul>
  </div>

  <div class="poll__content">
    <h2><%= link_to poll.title, poll %></h2>

    <% if poll.expired? || poll.owned_by?(current_user) %>
      <%= render 'shared/static-options', poll: poll %>
    <% else %>
      <%= render 'shared/options', poll: poll %>
    <% end %>

    <ul class="poll__actions">
      <li class="poll__actions__comments poll__actions__action">
        <%= link_to poll do %>
          <i class="icon-comment"></i>
          <span><%= pluralize(poll.comment_count, "comment") %></span>
        <% end %>
      </li>
      <% if !poll.owned_by?(current_user) %>
          <li class="poll__actions__action">
            <%= render 'shared/follow', poll: poll %>
          </li>
        <% end %>
      <li class="poll__actions__action">
        <%= link_to 'javascript:void(0)', id:"poll-copy-link-#{poll.id}", class: 'copy-link-poll', value: poll_url(poll) do %>
          <i class="icon-link"></i>
          <span id="poll-copy-span-<%= poll.id %>">copy link</span>
        <% end %>
      </li>
      <% if poll.owned_by?(current_user) %>
        <li class="poll__actions__action">
        <%= link_to poll_path(poll), method: :delete, id: '', class: '' do %>
            <i class="icon-trash"></i>
            <span>delete poll</span>
        <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</article>

app/views/shared/_reset-password.html.erb
<dialog hidden class="modal reset-password" id="reset-password">
  <div class="modal__inner">
    <div class="modal__top">
      <h2 class="modal__title">Password Reset</h2>
      <button href="#TODO" class="modal__cancel" data-module="modal" aria-controls="reset-password">Cancel<i class="icon-expired"></i></button>
    </div>

    <%= form_for(User.new, as: :user, url: password_path(:user) , html: { method: :put }) do |f| %>

      <div class="form__fields__field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>

      <div class="form__fields__action">
        <%= f.submit "Send reset password instructions", class: "form__button" %>
      </div>
    <% end %>
  </div>
</dialog>

app/views/shared/_signup.html.erb
<dialog hidden class="modal sign-up" id="sign-up">
  <div class="modal__inner">
    <div class="modal__top">
      <h2 class="modal__title">Sign up</h2>
      <button href="#TODO" class="modal__cancel" data-module="modal" aria-controls="sign-up">Cancel<i class="icon-expired"></i></button>
    </div>
    <%= form_for(User.new, as: :user, url: registration_path(:user), remote: true, html: {id: "signup-form"}) do |f| %>
      <div class="form__fields">
        <!-- Eror messages from Devise  -->
        <div id="signup-error-messages" class="sign-up__error-messages">
        </div>
        <div class="form__fields__field">
          <%= f.label :email %>
          <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
        </div>

        <div class="form__fields__field">
          <%= f.label :username %>
          <%= f.text_field :username, autofocus: true, autocomplete: "username" %>
        </div>

        <div class="form__fields__field">
          <%= f.label :password %>
          <% if @minimum_password_length %>
            <em class="sign-up__field__password__minchar">(<%= @minimum_password_length %> characters minimum)</em>
          <% end %>
          <%= f.password_field :password, autocomplete: "off" %>
        </div>

        <div class="form__fields__field">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, autocomplete: "off" %>
        </div>

        <div class="form__fields__action">
          <%= f.submit "Sign up", class: "form__button" %>
        </div>

        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      </div>
    <% end %>
  </div>
  <div class="form__bottom-prompt">
    <p>Already have an account?</p>
    <button href="#" data-module="modal" aria-controls="log-in">Log in</button>
  </div>
</dialog>